replicaCount: 1

revisionHistoryLimit: 3

image:
  repository: ghcr.io/bcgov/cappy
  pullPolicy: IfNotPresent
  tag: ""

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

# pvc:
#   storage: "100Mi"
#   formData:
#     storage: "100Mi"

db:
  host: "postgres"
  port: 5432
  name: "laravel"
  username: "laravel"
  password: "<app-db-password>"