apiVersion: apps/v1
kind: Deployment
metadata:
  name: cappy-app
  labels:
    app.kubernetes.io/name: cappy-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cappy-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cappy-app
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: cappy-app
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage-volume 
              mountPath: /var/www/storage
            - name: public-html-volume 
              mountPath: /var/www/html/public
          envFrom:
            - secretRef:
                name: cappy-secrets
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: cappy-secrets
                  key: MAIL_PORT
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: cappy-app-shared-pvc
        - name: public-html-volume 
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: 600